steps:
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'

- name: 'gcr.io/$PROJECT_ID/go-make'
  entrypoint: 'bash'
  args: ['-c', 'tar -zvcf gloo-dep-${BRANCH_NAME}.tar.gz ./gopath/pkg/dep']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gloo-dep-${BRANCH_NAME}.tar.gz', 'gs://solo-public-cache/gloo']

timeout: 1800s